
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 * The {@code IconHolder} class is responsible for managing a collection of
 * image icons. It provides functionality to add, retrieve, sort, reverse and
 * animate these icons.
 */
public class IconHolder {
	/** A map storing all the image icons against their respective names as keys. */
	private Map<String, ImageIcon> imageIcons;

	/** Timer used for the animation feature. */
	private Timer animationTimer;

	/**
	 * Default constructor that initializes the image icons map.
	 */
	public IconHolder() {
		imageIcons = new HashMap<String, ImageIcon>();
	}

	/**
	 * Adds or replaces an ImageIcon object in the icon map with the given name as
	 * the key. If the key already exists in the map, the associated ImageIcon
	 * object will be replaced.
	 *
	 * @param name The name key for the ImageIcon.
	 * @param icon The ImageIcon object to be added.
	 */
	public void addIcon(String name, ImageIcon icon) {
		imageIcons.put(name, icon);
	}

	/**
	 * Adds an ImageIcon object to the icon map using the given path. The name key
	 * is extracted from the path using the fileRenaming method.
	 *
	 * @param path The Path object representing the file path of the image.
	 */
	public void addIcon(Path path) {
		addIcon(fileRenaming(path), new ImageIcon(path.toAbsolutePath().toString()));
	}

	/**
	 * Adds a list of ImageIcon objects to the icon map with unique keys. The keys
	 * are generated by appending the index of each icon in the list to the provided
	 * name parameter.
	 *
	 * @param name  The base name key for the ImageIcons. The index will be appended
	 *              to this name for each icon.
	 * @param icons The list of ImageIcon objects to be added.
	 */
	public void addIcon(String name, List<ImageIcon> icons) {
		for (int i = 0; i < icons.size(); i++) {
			addIcon((name + i), icons.get(i));
		}
	}

	/**
	 * Retrieves an ImageIcon object associated with the given name.
	 * 
	 * @param name The name key of the ImageIcon to retrieve.
	 * @return The ImageIcon object if found, or null if the name key does not
	 *         exist.
	 */
	public ImageIcon getIcon(String name) {
		if (imageIcons.containsKey(name)) {
			return imageIcons.get(name);
		} else {
			System.out.println("Icon Holder does not currently contain " + name);
			return null;
		}
	}

	/**
	 * Generates a List of all ImageIcons present in the IconHolder
	 *
	 * @return A list of all ImageIcons in the IconHolder
	 */
	public List<ImageIcon> getIcons() {
		List<ImageIcon> icons = new ArrayList<>();
		for (Map.Entry<String, ImageIcon> entry : imageIcons.entrySet()) {
			icons.add(entry.getValue());
		}
		return icons;
	}

	/**
	 * Retrieves all icons that have a name starting with the given prefix.
	 *
	 * @param prefix The prefix used to find the images.
	 * 
	 * @return a new IconHolder containing all images with matching prefixes
	 */
	public IconHolder getIcons(String prefix) {
		IconHolder icons = new IconHolder();
		for (Map.Entry<String, ImageIcon> entry : imageIcons.entrySet()) {
			if (entry.getKey().startsWith(prefix)) {
				icons.addIcon(entry.getKey(), entry.getValue());
			}
		}
		if (icons.isEmpty()) {
			System.out.println("No icons found with the prefix: " + prefix);
			return new IconHolder();
		}
		icons.sort();
		return icons;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("IconHolder:\n");
		sb.append("Number of Icons: ").append(size()).append("\n");

		if (!imageIcons.isEmpty()) {
			sb.append("Icons:\n");
			for (Map.Entry<String, ImageIcon> entry : imageIcons.entrySet()) {
				sb.append("Name: ").append(entry.getKey()).append("\n");
				sb.append("Path: ").append(entry.getValue().getDescription()).append("\n");
			}
		}

		return sb.toString();
	}

	/**
	 * Returns the size of the IconHolder
	 * 
	 * @return The size of the IconHolder
	 */
	public int size() {
		return imageIcons.size();
	}

	/**
	 * Checks to see if the IconHolder has values
	 * 
	 * @return true = empty, false = has at least 1 entry
	 */
	public boolean isEmpty() {
		if (imageIcons.isEmpty()) {
			return true;
		} else {
			return false;
		}
	}

	/**
	 * Sorts the icons based on their names.
	 */
	public void sort() {
		Map<String, ImageIcon> sortedIcons = new TreeMap<>(imageIcons);
		imageIcons = sortedIcons;
	}

	/**
	 * Reverses the order of the keys in the IconHolder. If the keys are not already
	 * sorted, this method first sorts them and then reverses the order, so that
	 * a->z would go z->a. The reversed entries are stored in a LinkedHashMap to
	 * preserve the reversed ordering.
	 */
	public void reverse() {
		sort();

		Map<String, ImageIcon> reversedIcons = new LinkedHashMap<>();
		List<Map.Entry<String, ImageIcon>> entries = new ArrayList<>(imageIcons.entrySet());
		Collections.reverse(entries);

		for (Map.Entry<String, ImageIcon> entry : entries) {
			reversedIcons.put(entry.getKey(), entry.getValue());
		}
		imageIcons = reversedIcons;
	}

	/**
	 * Constructs the GUI by reading a text file for image names, loading said image
	 * names from the file directory and populating the imageIcons map.
	 */
	public void construct() {
		try {
			System.out.println("Attempting to load images...");

			InputStream listStream = getClass().getResourceAsStream("/icon_list.txt");
			if (listStream == null) {
				System.err.println("Resource list not found!");
				return;
			}

			BufferedReader reader = new BufferedReader(new InputStreamReader(listStream));
			String imageName;
			while ((imageName = reader.readLine()) != null) {
				String path = imageName;
				URL imageUrl = getClass().getResource(path);
				if (imageUrl != null) {
					ImageIcon icon = new ImageIcon(imageUrl);
					addIcon(fileRenaming(Paths.get(imageName)), icon);
				} else {
					System.err.println("Could not load image: " + path);
				}
			}

			System.out.println("Images loaded! IconHolder generated!");

		} catch (IOException e) {
			System.err.println("Error reading from file. Images not loaded.");
			e.printStackTrace();
		}
	}

	/**
	 * Extracts the filename (without the extension) from the given path.
	 *
	 * @param path The path from which to extract the filename.
	 * @return The filename without the extension.
	 */
	private String fileRenaming(Path path) {
		String name = path.getFileName().toString();
		int dotIndex = name.lastIndexOf(".");
		if (dotIndex > 0) {
			name = name.substring(0, dotIndex);
		}
		return name;
	}

	/**
	 * Animates all ImageIcon objects in the IconHolder by displaying them on the
	 * given JLabel. Cycles through each image every 'length' milliseconds.
	 *
	 * @param delay The time in milliseconds between frames.
	 * @param label The JLabel to display the animation.
	 */
	public void playAnimation(int delay, JLabel label) {
		this.playAnimation(delay, label, null);
	}

	/**
	 * Animates ImageIcon objects with a given prefix by displaying them on the
	 * given JLabel. Cycles through matching images every 'length' milliseconds.
	 *
	 * @param prefix The prefix for selecting images.
	 * @param delay  The time in milliseconds between frames.
	 * @param label  The JLabel to display the animation.
	 */
	public void playAnimation(String prefix, int delay, JLabel label) {
		IconHolder temp = this.getIcons(prefix);
		temp.playAnimation(delay, label, null);
	}

	/**
	 * Starts the animation of icons on the specified JLabel. This method will
	 * display each image in the IconHolder one by one on the label with a delay
	 * specified by the 'delay' parameter. If 'onComplete' is provided, it will be
	 * executed after the animation ends.
	 *
	 * @param delay      The interval in milliseconds between image transitions.
	 * @param label      The JLabel on which the animation is displayed.
	 * @param onComplete An optional runnable that's executed after the animation
	 *                   ends.
	 */
	public void playAnimation(int delay, JLabel label, Runnable onComplete) {
		if (!label.isVisible()) {
			label.setVisible(true);
		}
		List<ImageIcon> animation = this.getIcons();
		int[] currentIndex = { 0 };
		animationTimer = new Timer(delay, e -> {
			label.setIcon(animation.get(currentIndex[0]));
			label.revalidate();
			label.repaint();

			if (currentIndex[0] == animation.size() - 1) {
				animationTimer.stop();
				if (onComplete != null) {
					onComplete.run();
				}
				return;
			}
			currentIndex[0] = (currentIndex[0] + 1) % animation.size();
		});
		animationTimer.start();
	}

	/**
	 * Animates only the icons with the specified prefix on the given JLabel. This
	 * method will display each matching image in the IconHolder one by one on the
	 * label with a delay specified by the 'delay' parameter. If 'onComplete' is
	 * provided, it will be executed after the animation ends.
	 *
	 * @param prefix     The prefix to select which icons to animate.
	 * @param delay      The interval in milliseconds between image transitions.
	 * @param label      The JLabel on which the animation is displayed.
	 * @param onComplete An optional runnable that's executed after the animation
	 *                   ends.
	 */
	public void playAnimation(String prefix, int delay, JLabel label, Runnable onComplete) {
		IconHolder temp = this.getIcons(prefix);
		temp.sort();
		temp.playAnimation(delay, label, onComplete);
	}

}
